.TH dot-obdgpslogger 5
.SH NAME
$HOME/.obdgpslogger \- configuration file for obdgpslogger

.SH DESCRIPTION
.IX Header "DESCRIPTION"
Configuration file for obdgpslogger

.B obddevice=<string>
Full path to obd device entry [typically /dev/something]

.B gpsdevice=<string>
Full path to gps device entry [typically /dev/something]

.B log_columns=<string>
Command-separated list of db_column entries to log. These are
probably things you want to draw from "obdgpslogger -p"

.B samplerate=<integer>
Number of samples to take per second

.B optimisations=<integer>
Set to 1 to enable ELM optimisations

.SH SEE ALSO
.IX Header "SEE ALSO"
.BR "obdgpslogger(1), obdgui(1)"

.SH AUTHORS
Gary "Chunky Ks" Briggs <chunky@icculus.org>

