.TH obd2csv 1
.SH NAME
obd2csv \- Convert obdlogger(1) logs to csv files

.SH SYNOPSIS
.B obd2csv [ options ]

.SH DESCRIPTION
.IX Header "DESCRIPTION"
Convert obdlogger(1) logs to csv files

.SH OPTIONS
.IX Header "OPTIONS"
.IP "-o|--out <output filename>"
Output to this .csv file
.IP "-d|--db <database>"
Work from logs stored in this database file
.IP "-v|--version"
Print out version number and exit.
.IP "-h|--help"
Print out help and exit.
 
.SH SEE ALSO
.IX Header "SEE ALSO"
.BR "obdlogger(1), obd2kml(1), obdgui(1)"

.SH AUTHORS
Gary "Chunky Ks" Briggs <chunky@icculus.org>

