.TH obdsim 1
.SH NAME
obdsim \- Simulate an ELM327 device

.SH SYNOPSIS
.B obdsim [ options ]

.SH DESCRIPTION
.IX Header "DESCRIPTION"
obdsim simulates and ELM327 device using unix pseudo-terminals

.SH OPTIONS
.IX Header "OPTIONS"
.IP "-s|--seed <seed>"
Generator-specific seed. See section titled PLUGIN SEEDS below for
more information
.IP "-g|--generator <generator-name>"
Choose a generator. A list of valid ones is output by --help
.IP "-o|--launch-logger"
Takes an [admittedly weak and hard-coded] attempt at launching
obdgpslogger attached to the simulator in question.
.IP "-c|--launch-screen"
Takes an [admittedly weak and hard-coded] attempt at launching
screen attached to the simulator in question. To close that screen window,
use ctrl-a, k.
.IP "-e|--genhelp"
Print out help for the generator specified with -g, and exit.
.IP "-v|--version"
Print out version number and exit.
.IP "-h|--help"
Print out help and exit.
 
.SH PLUGIN SEEDS
.IX Header "PLUGIN SEEDS"
Each plugin takes a seed. Here's what those seeds are:
.IP Random
[Optional] It's a random seed
.IP Cycle
[Optional] [cycle time in seconds[,number of gears]]
.IP Logger
[Obligatory] Filename of an obdgpslogger logfile
.IP dlopen
[Obligatory] Filename of a dynamically linked library
.IP Socket
[Obligatory] ip-or-hostname:port
.IP DBus
[Obligatory] Filename of a configuration file for the plugin
.IP gui_fltk
[Irrelevant] Ignores the passed seed

.SH SEE ALSO
.IX Header "SEE ALSO"
.BR "obdgpslogger(1), obd2kml(1), obd2csv(1), obdgui(1), obdlogrepair(1), obdsim-dbus(5)"

.SH AUTHORS
Gary "Chunky Ks" Briggs <chunky@icculus.org>

