#ifndef OBDCONFIG_H
#define OBDCONFIG_H

#cmakedefine OBD_GPSD_PIDFILE "@OBD_GPSD_PIDFILE@"
#cmakedefine OBD_GPSD_CONTROL_SOCKET "@OBD_GPSD_CONTROL_SOCKET@"
#cmakedefine OBD_DEFAULT_GPSPORT "@OBD_DEFAULT_GPSPORT@"
#cmakedefine OBD_DEFAULT_SERIALPORT "@OBD_DEFAULT_SERIALPORT@"
#cmakedefine OBD_DEFAULT_DATABASE "@OBD_DEFAULT_DATABASE@"
#cmakedefine OBD_CONFIG_FILENAME "@OBD_CONFIG_FILENAME@"

#endif // OBDCONFIG_H

